package edu.rit.se.design.arcode.fspec2code;

import com.sun.nio.sctp.MessageInfo;

import javax.management.remote.rmi.RMIServer;
import javax.security.auth.Destroyable;
import javax.security.auth.Subject;
import javax.security.auth.SubjectDomainCombiner;
import javax.security.auth.callback.CallbackHandler;
import javax.security.auth.kerberos.KerberosPrincipal;
import javax.security.auth.login.AccountException;
import javax.security.auth.login.AppConfigurationEntry;
import javax.security.auth.login.Configuration;
import javax.security.auth.login.LoginContext;
import java.io.InputStream;
import java.io.PrintStream;
import java.rmi.MarshalledObject;
import java.rmi.Naming;
import java.rmi.RMISecurityManager;
import java.rmi.Remote;
import java.rmi.activation.*;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.RMIClientSocketFactory;
import java.rmi.server.RMIServerSocketFactory;
import java.rmi.server.RMISocketFactory;
import java.rmi.server.UnicastRemoteObject;
import java.security.*;
import java.util.*;

/**
 * @author Ali Shokri (as8308@rit.edu)
 */
public class GeneratedCodeTest {

    /*Generated by FSpec2Code*/
    public void jaasAPIUsage_1(CallbackHandler callbackHandler, String string){
        try{
            Subject subject = new Subject();
            LoginContext loginContext = new LoginContext(string, subject, callbackHandler);
            loginContext.login();
        } catch(Exception e){
            e.printStackTrace();
        }
    }

}
